---
- name: Web Server Uninstall
  hosts: workstation.example.com
  become: yes
  tasks:
  - block:
    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: yes
  - block:
    - name: httpd enabled and running
      service:
        name: httpd
        enabled: false
        state: stopped
  - block:
    - name: latest httpd version installed
      yum:
        name: httpd
        state: absent
  - block:
    - name: test html page
      file:
        state: absent
        path: /var/www/html/index.html
